name = "figma-discord-webhook"
type = "webpack"

account_id = "fd0a782f3c3fee3f9a959026e64400cb"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-14"

kv_namespaces = [
     { binding = "FIGMA_DISCORD_WEBHOOK", preview_id = "1d0ad2e6b16844068351da1db316b13f", id = "0fe14d6a2cf542bc8a52ac1072f69670" }
]

# [secrets]
# FIGMA_PASSCODE